server:
  port: 8090

# datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306?useUnicode=true&characterEncoding=utf8&serverTime=UTC
    username: root
    password: 111111

# mybatis
mybatis:
  type-aliases-package: com.edu.hzau.cocs.swinedb.pojo
  mapper-locations: classpath:mapper/*.xml
